//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardInfo
    {
        public int cardno { get; set; }
        public Nullable<System.DateTime> expdate { get; set; }
        public int cvvno { get; set; }
        public long balance { get; set; }
    }
}
